### ISSUE TITLE
Better build system & compilers

### ISSUE THREAD

**Issue by Leurak** [Leurak/MEMZ#21]
The build system, especially for the MBR payload, sucks.

There are better ways to do that, like Makefiles.

I also wanna drop the Visual C++ Compiler, as that needs some dumb workarounds and it would maybe even possible to port MEMZ down to Windows 2000 or even 9X, if all the required APIs are available (which MSDN does not tell me).

**Comment by Thesola10** [comment]
I'm on it! rewriting the MBR payload. Oh, and is `startanimation` the entrypoint for the payload?

**Comment by Leurak** [comment]
I think I'll rewrite the payload myself, so please make only changes required for the Cygwin/LD system.

**Comment by Thesola10** [comment]
Ok, can you check my fork Thesola10/MEMZ i just pushed some changes.

**Comment by Leurak** [comment]
Why did you made a linker script for the MBR payload?

**Comment by Thesola10** [comment]
To leave space for patching dynamic data eg pointers to a MBR backup. In the works.

**Comment by Leurak** [comment]
I wonder if the whole backup always gets saved at once or if it gets split due to fragmentation

**Comment by Thesola10** [comment]
Oh just looked through and it seems all the linking is embedded in kernel.asm... Will try and decipher it

**Comment by Leurak** [comment]
You also forgot the compressor (at least I didn't found it)

Am 12.04.2017 12:27 schrieb "Karim Vergnes" <notifications@github.com>:

**Comment by Thesola10** [comment]
got a target for it i'll push the latest changes

**Comment by Thesola10** [comment]
build goes, but nyan cat sounds like a chainsaw.

**Comment by Leurak** [comment]
Do you use the right midi? Or it's a compressor issue. But if decompressing fails, the animation has to be wrong too. I'll look at the code. But I can't test it currently.

**Comment by Thesola10** [comment]
Animation: first frame goes. That's it.

**Comment by Leurak** [comment]
Then the compression/decompression is wrong. I will later on compress the code itself too, so the only non-compressed thing left will be the decompressor. So the decompression has to be totally stable, or else it corrupts its own code...

**Comment by Thesola10** [comment]
i don't think I have the right midi... could you send me the one you use?

**Comment by Leurak** [comment]
By the way, way do you use a linker script? You can align directly in NASM too, as I did before.

**Comment by Leurak** [comment]
If only the first frame works, it's a compressor issue.

**Comment by Thesola10** [comment]
I'd like to do the opposite: put this NASM link in the script to makes matters easier

**Comment by Thesola10** [comment]
ok didn't touch the compressor code for now since it was building nicely
but i'll see

**Comment by Leurak** [comment]
Are you building the decompressor? The actual entrypoint is the decompression routine, not the start of the animation.

**Comment by Thesola10** [comment]
OH SH*T

**Comment by Leurak** [comment]
The LD script would only make sense if you'll use Gnu's own assembler

**Comment by Thesola10** [comment]
Not necessarily, nasm seems to integrate nicely. Just the include compressor not working, LD didn't find the start symbol I created from the beginning instructions

**Comment by Leurak** [comment]
Are you linking for 16-bit code? I guess that could be another problem. I never used Makefiles or even LD scripts, so I can't tell.

I'll port it to 32 bit mode anyways. Windows won't even run on an 80286 :D

**Comment by Thesola10** [comment]
I am linking for i386 flat, because of compat mode it's 16bit anyway

**Comment by Thesola10** [comment]
strings says the symbol is there, ld says it's not...

**Comment by Leurak** [comment]
Is it in the right section?

**Comment by Thesola10** [comment]
wait... you're definitely in my computer cuz that's my EXACT mistake...

**Comment by Thesola10** [comment]
well now the entry point is in .text and... well... still error.

**Comment by Thesola10** [comment]
wait i forgot global

**Comment by Thesola10** [comment]
Okay start point fixed, decompress issue not.

**Comment by Thesola10** [comment]
Lemme check: Compressed data starts at `0x0000` and code (section text) at `0x7c00` right?

**Comment by Leurak** [comment]
I still don't understand the need of a LD script, but you can still do it if you want to.

The other thing is porting the C code to MinGW. It'll be awesome if the MBR payload gets linked into the C code, without manually including it as an array.

**Comment by Thesola10** [comment]
well MinGW works almost like the native Linux tools I work on, and the linker makes the kernel.asm cleaner.

**Comment by Leurak** [comment]
I guess you'll have to use the right segments. It's not at 0x0000, it's offset by either DS or ES (not looking currently).

**Comment by Leurak** [comment]
That's true. Could you join my Discord Server so we can talk there? GH Issues are getting a bit overloaded with chat.

**Comment by Thesola10** [comment]
wait installing but okay. No voice tho

**Comment by Leurak** [comment]
I'm not using voice anyways.

**Comment by Thesola10** [comment]
Done installing

**Comment by Thesola10** [comment]
hello?

**Comment by Leurak** [comment]
Sorry, wasn't online. You can find it on my Twitter.

**Comment by Thesola10** [comment]
#24 for reference

**Comment by Leurak** [comment]
MBR is done, C is now ported to MinGW but still does not work well. Will close this when the C part is fixed and restructured.
